### ISSUE TITLE
problem with installing the plugin

### ISSUE THREAD

**Issue by davidgruebl** [newrelic/newrelic-cordova-ios#2]
Installation as described in the readme does not work as authentication is required:
```console
$ cordova plugin add https://source.datanerd.us/mobile/newrelic-cordova-ios
Fetching plugin "https://source.datanerd.us/mobile/newrelic-cordova-ios" via git clone
Username for 'https://source.datanerd.us':
```
I installed the plugin using this repo:
```console
$ cordova plugin add https://github.com/newrelic/newrelic-cordova-ios.git
```
and followed the rest of the instructions provided. This did not cause any errors however no data appears in the New Relic backend. This did work with https://github.com/jeff-french/newrelic-cordova

As the new New Relic backend recommended to upgrade I thought this official implementation would be the way to go.

**Comment by bryce-newrelic** [comment]
I corrected this
